name: CI for PR Merge

on:
  pull_request:
    branches: [ main, test_main ]
  workflow_call:

jobs:
  ubuntu_build:
    runs-on: ubuntu-20.04
    env:
      CC: clang
    steps:
    - uses: actions/checkout@v2
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: gha_create_release_test
    - name: Build and Test
      shell: bash
      run: |
        bazelisk test //...

